import type { World, WorldId } from "./types";
import { validateWorlds } from "./validateWorlds";
import musicPrompts from "./musicPrompts.json";

/**
 * Assets live under `public/worlds/<world-id>/{scene,ambience,events}/`.
 * Any referenced file may be missing: that layer stays silent / falls back, nothing else breaks.
 */
export const worlds: World[] = [
  {
    id: "orbital-station",
    name: "Orbital Station",
    year: 2187,
    scene: { type: "image", src: "/worlds/orbital-station/scene/orbital-station.png" },
    music: {
      prompt: musicPrompts["orbital-station"],
      tempo: [66, 78],
      keys: ["D", "E", "F", "G", "A"],
      scale: "major",
      progressions: ["1-4-1-4", "2-5-1-6", "1-6-2-5", "4-3-2-1"],
      chords: { style: "ninth", rhythm: "sustain", barsPerChord: 2 },
      density: { drums: 0.22, bass: 0.3, melody: 0.12 },
      melodyScale: "full",
      space: { brightness: 0.32, softness: 0.85 },
      reverb: { amount: 0.7, decay: 3.4, damping: 0.78, preDelay: 0.028 },
      sound: {
        kickSoftness: 0.82,
        snareBrightness: 0.28,
        hatBrightness: 0.32,
        chordWarmth: 0.82,
        leadBrightness: 0.35,
        textureAmount: 0.08,
      },
      nextStartMode: "main",
      form: [
        { kind: "intro", bars: 8, drums: 0, bass: 0, melody: 0, tone: 0.75 },
        { kind: "a", bars: 8, drums: 0, bass: 0.6, melody: 0 },
        { kind: "a", bars: 8, drums: 0.45, bass: 0.8, melody: 0, variation: true },
        { kind: "b", bars: 8, drums: 1, bass: 1, melody: 1 },
        { kind: "a", bars: 8, drums: 0.8, bass: 0.8, melody: 0.6 },
        { kind: "breakdown", bars: 8, drums: 0, bass: 0, melody: 0, tone: 0.7, wet: 1.4 },
        { kind: "a", bars: 8, drums: 0.9, bass: 1, melody: 0.8, variation: true },
      ],
      groove: { swing: 0.08, timingHumanization: 0.006, velocityHumanization: 0.06 },
      tape: 0.3,
    },
    ambience: [
      {
        id: "engine",
        name: "Engine Hum",
        src: "/worlds/orbital-station/ambience/engine.wav",
        defaultVolume: 0.34,
      },
      {
        id: "vent",
        name: "Ventilation",
        src: "/worlds/orbital-station/ambience/vent.wav",
        defaultVolume: 0.24,
      },
      {
        id: "radio",
        name: "Radio Chatter",
        src: "/worlds/orbital-station/ambience/radio.wav",
        defaultVolume: 0.12,
      },
    ],
    effects: {
      stars: { intensity: 0.22 },
      particles: { type: "atmosphere", intensity: 0.14, color: [180, 205, 215] },
      fog: { intensity: 0.1, color: [186, 210, 214] },
      flicker: { intensity: 0.05, style: "screen" },
    },
    events: [
      {
        id: "shuttle-pass",
        type: "flyby",
        asset: "/worlds/orbital-station/events/shuttle.png",
        direction: "either",
        top: [14, 34],
        scale: 0.9,
        lightColor: [150, 220, 255],
        weight: 3,
        minDelay: 30_000,
        maxDelay: 80_000,
        cooldown: 60_000,
        duration: 12_000,
      },
      {
        id: "docking-beacon",
        type: "pulse",
        pattern: "beacon",
        color: [255, 120, 90],
        x: 78,
        y: 22,
        size: 18,
        intensity: 0.45,
        weight: 3,
        minDelay: 20_000,
        maxDelay: 50_000,
        duration: 2_400,
      },
      {
        id: "docking-announcement",
        type: "sound",
        sound: { src: "/worlds/orbital-station/events/docking-announcement.wav", volume: 0.42 },
        weight: 2,
        minDelay: 70_000,
        maxDelay: 160_000,
        cooldown: 150_000,
        duration: 5_000,
      },
      {
        id: "meteor",
        type: "streak",
        angle: 24,
        weight: 1,
        minDelay: 120_000,
        maxDelay: 300_000,
        cooldown: 240_000,
        duration: 1_400,
      },
    ],
  },
  {
    id: "neon-city",
    name: "Neon City",
    year: 2194,
    scene: { type: "image", src: "/worlds/neon-city/scene/neon-city.png" },
    music: {
      prompt: musicPrompts["neon-city"],
      tempo: [80, 94],
      keys: ["C", "D", "F", "G", "A"],
      scale: "aeolian",
      progressions: ["1-6-3-7", "1-4-7-3", "1-7-6-7", "1-4-5-1"],
      chords: { style: "seventh", rhythm: "pulse", barsPerChord: 1 },
      density: { drums: 0.58, bass: 0.7, melody: 0.32 },
      melodyScale: "pentatonic",
      space: { brightness: 0.48, softness: 0.3 },
      reverb: { amount: 0.3, decay: 1.35, damping: 0.32, preDelay: 0.012 },
      sound: {
        kickSoftness: 0.38,
        snareBrightness: 0.55,
        hatBrightness: 0.5,
        chordWarmth: 0.48,
        leadBrightness: 0.55,
        textureAmount: 0.28,
      },
      nextStartMode: "main",
      form: [
        { kind: "intro", bars: 4, drums: 0, bass: 0, melody: 0, tone: 0.45 },
        { kind: "a", bars: 8, drums: 0.8, bass: 0.8, melody: 0 },
        { kind: "a", bars: 8, drums: 0.85, bass: 0.9, melody: 0.6, variation: true },
        { kind: "b", bars: 8, drums: 1, bass: 1, melody: 1 },
        { kind: "a", bars: 8, drums: 0.8, bass: 0.8, melody: 0.5 },
        { kind: "breakdown", bars: 4, drums: 0.35, bass: 0.4, melody: 0, tone: 0.65, wet: 1.3 },
        { kind: "a", bars: 8, drums: 1, bass: 1, melody: 0.8, variation: true },
      ],
      groove: { swing: 0.16, timingHumanization: 0.011, velocityHumanization: 0.1 },
      tape: 0.55,
    },
    ambience: [
      {
        id: "rain",
        name: "Rain",
        src: "/worlds/neon-city/ambience/rain.wav",
        defaultVolume: 0.46,
      },
      {
        id: "traffic",
        name: "Distant Traffic",
        src: "/worlds/neon-city/ambience/traffic.wav",
        defaultVolume: 0.24,
      },
      {
        id: "crowd",
        name: "City Hum",
        src: "/worlds/neon-city/ambience/crowd.wav",
        defaultVolume: 0.18,
      },
    ],
    effects: {
      rain: { intensity: 0.78 },
      particles: { type: "atmosphere", intensity: 0.12, color: [185, 170, 220] },
      fog: { intensity: 0.24, color: [170, 164, 214] },
      flicker: { intensity: 0.12, style: "neon" },
    },
    events: [
      {
        id: "hovercar-pass",
        type: "flyby",
        asset: "/worlds/neon-city/events/hovercar.png",
        direction: "either",
        top: [18, 42],
        scale: 0.7,
        lightColor: [255, 90, 190],
        weight: 4,
        minDelay: 18_000,
        maxDelay: 50_000,
        cooldown: 25_000,
        duration: 8_000,
      },
      {
        id: "sign-glitch",
        type: "pulse",
        pattern: "glitch",
        color: [80, 220, 255],
        x: 24,
        y: 30,
        size: 26,
        intensity: 0.42,
        weight: 3,
        minDelay: 25_000,
        maxDelay: 60_000,
        duration: 1_800,
      },
      {
        id: "distant-siren",
        type: "sound",
        sound: { src: "/worlds/neon-city/events/siren.wav", volume: 0.3 },
        weight: 1,
        minDelay: 90_000,
        maxDelay: 240_000,
        cooldown: 200_000,
        duration: 7_000,
      },
      {
        id: "distant-lightning",
        type: "pulse",
        pattern: "flash",
        color: [200, 215, 255],
        x: 62,
        y: 8,
        size: 90,
        intensity: 0.2,
        weight: 1,
        minDelay: 150_000,
        maxDelay: 360_000,
        cooldown: 300_000,
        duration: 1_600,
      },
    ],
  },
  {
    id: "centauri-a",
    name: "Centauri A",
    year: 2247,
    scene: { type: "image", src: "/worlds/centauri-a/scene/centauri-a.png" },
    music: {
      prompt: musicPrompts["centauri-a"],
      tempo: [58, 72],
      keys: ["D", "E", "G", "A", "C"],
      scale: "dorian",
      progressions: ["1-4-1-4", "4-3-2-1", "1-4-5-1"],
      chords: { style: "ninth", rhythm: "sustain", barsPerChord: 2 },
      density: { drums: 0.12, bass: 0.22, melody: 0.08 },
      melodyScale: "pentatonic",
      space: { brightness: 0.3, softness: 0.62 },
      reverb: { amount: 0.82, decay: 4.2, damping: 0.84, preDelay: 0.045 },
      sound: {
        kickSoftness: 0.94,
        snareBrightness: 0.16,
        hatBrightness: 0.18,
        chordWarmth: 0.92,
        leadBrightness: 0.42,
        textureAmount: 0.16,
      },
      nextStartMode: "main",
      form: [
        { kind: "intro", bars: 8, drums: 0, bass: 0, melody: 0, tone: 0.7, wet: 1.15 },
        { kind: "a", bars: 8, drums: 0, bass: 0.45, melody: 0 },
        { kind: "a", bars: 8, drums: 0.35, bass: 0.6, melody: 0, variation: true },
        { kind: "breakdown", bars: 8, drums: 0, bass: 0, melody: 0, tone: 0.65, wet: 1.35 },
        { kind: "b", bars: 8, drums: 0.7, bass: 0.75, melody: 1 },
        { kind: "a", bars: 8, drums: 0.4, bass: 0.55, melody: 0.35 },
        { kind: "a", bars: 8, drums: 0.25, bass: 0.4, melody: 0.2, variation: true, tone: 0.75, wet: 1.2 },
      ],
      groove: { swing: 0.04, timingHumanization: 0.005, velocityHumanization: 0.05 },
      tape: 0.18,
    },
    ambience: [
      {
        id: "habitat-hum",
        name: "Habitat Hum",
        src: "/worlds/centauri-a/ambience/habitat-hum.wav",
        defaultVolume: 0.28,
      },
      {
        id: "desert-wind",
        name: "Desert Wind",
        src: "/worlds/centauri-a/ambience/desert-wind.wav",
        defaultVolume: 0.22,
      },
      {
        id: "research-electronics",
        name: "Research Electronics",
        src: "/worlds/centauri-a/ambience/research-electronics.wav",
        defaultVolume: 0.14,
      },
      {
        id: "radio-static",
        name: "Radio Static",
        src: "/worlds/centauri-a/ambience/radio-static.wav",
        defaultVolume: 0.08,
      },
    ],
    effects: {
      particles: { type: "atmosphere", intensity: 0.32, color: [205, 160, 105] },
      fog: { intensity: 0.28, color: [196, 148, 88] },
      stars: { intensity: 0.06 },
    },
    events: [
      {
        id: "survey-drone",
        type: "flyby",
        asset: "/worlds/centauri-a/events/survey-drone.png",
        direction: "either",
        top: [12, 28],
        scale: 0.45,
        lightColor: [255, 176, 96],
        weight: 3,
        minDelay: 70_000,
        maxDelay: 160_000,
        cooldown: 90_000,
        duration: 11_000,
      },
      {
        id: "research-beacon",
        type: "pulse",
        pattern: "beacon",
        color: [255, 170, 90],
        x: 72,
        y: 46,
        size: 14,
        intensity: 0.28,
        weight: 2,
        minDelay: 90_000,
        maxDelay: 200_000,
        cooldown: 120_000,
        duration: 2_400,
      },
      {
        id: "meteor",
        type: "streak",
        angle: 18,
        weight: 1,
        minDelay: 180_000,
        maxDelay: 420_000,
        cooldown: 300_000,
        duration: 1_400,
      },
      {
        id: "radio-transmission",
        type: "sound",
        sound: { src: "/worlds/centauri-a/events/radio-transmission.mp3", volume: 0.22 },
        weight: 1,
        minDelay: 200_000,
        maxDelay: 480_000,
        cooldown: 360_000,
        duration: 4_000,
      },
    ],
  },
];

if (process.env.NODE_ENV !== "production") {
  validateWorlds(worlds);
}

export const worldIds: readonly WorldId[] = worlds.map((world) => world.id);

export const defaultWorldId: WorldId = worlds[0].id;

export function getWorldById(id: WorldId): World {
  return worlds.find((world) => world.id === id) ?? worlds[0];
}
